//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Box.People {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Box.People.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone has already started an export before you, press F5 to refresh the page..
        /// </summary>
        public static string Already_Exporting {
            get {
                return ResourceManager.GetString("Already_Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by email.
        /// </summary>
        public static string Contact_By_Email {
            get {
                return ResourceManager.GetString("Contact_By_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by mail.
        /// </summary>
        public static string Contact_By_Mail {
            get {
                return ResourceManager.GetString("Contact_By_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by SMS.
        /// </summary>
        public static string Contact_By_Sms {
            get {
                return ResourceManager.GetString("Contact_By_Sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact1 {
            get {
                return ResourceManager.GetString("Contact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on link below to download the file.
        /// </summary>
        public static string Download_File {
            get {
                return ResourceManager.GetString("Download_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an e-mail address.
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you accept receive newsletter through its email?.
        /// </summary>
        public static string EmailOptIn {
            get {
                return ResourceManager.GetString("EmailOptIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail address is already in use.
        /// </summary>
        public static string EmailsIsInvalid {
            get {
                return ResourceManager.GetString("EmailsIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export People.
        /// </summary>
        public static string Export_People {
            get {
                return ResourceManager.GetString("Export_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting.
        /// </summary>
        public static string Exporting {
            get {
                return ResourceManager.GetString("Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the following information.
        /// </summary>
        public static string FormSubHead {
            get {
                return ResourceManager.GetString("FormSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man.
        /// </summary>
        public static string Gender_Man {
            get {
                return ResourceManager.GetString("Gender_Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman.
        /// </summary>
        public static string Gender_Woman {
            get {
                return ResourceManager.GetString("Gender_Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People from group .
        /// </summary>
        public static string Group_Detail_Text {
            get {
                return ResourceManager.GetString("Group_Detail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone.
        /// </summary>
        public static string Group_Everyone {
            get {
                return ResourceManager.GetString("Group_Everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person from every group.
        /// </summary>
        public static string Group_Everyone_Detail {
            get {
                return ResourceManager.GetString("Group_Everyone_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last export.
        /// </summary>
        public static string Last_Export {
            get {
                return ResourceManager.GetString("Last_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you accept receive newsletter by mail?.
        /// </summary>
        public static string MailOptIn {
            get {
                return ResourceManager.GetString("MailOptIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Field.
        /// </summary>
        public static string MarketField {
            get {
                return ResourceManager.GetString("MarketField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow contact by.
        /// </summary>
        public static string NewsletterOptions {
            get {
                return ResourceManager.GetString("NewsletterOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click in start button to start an export..
        /// </summary>
        public static string No_Export_Message {
            get {
                return ResourceManager.GetString("No_Export_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no name.
        /// </summary>
        public static string no_name {
            get {
                return ResourceManager.GetString("no_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoOptIn {
            get {
                return ResourceManager.GetString("NoOptIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register updated.
        /// </summary>
        public static string Optin_Updated_Message {
            get {
                return ResourceManager.GetString("Optin_Updated_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string OptinAll {
            get {
                return ResourceManager.GetString("OptinAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only e-mail.
        /// </summary>
        public static string OptinOnlyEmail {
            get {
                return ResourceManager.GetString("OptinOnlyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Mail.
        /// </summary>
        public static string OptinOnlyMail {
            get {
                return ResourceManager.GetString("OptinOnlyMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only SMS.
        /// </summary>
        public static string OptinOnlySMS {
            get {
                return ResourceManager.GetString("OptinOnlySMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept e-mail.
        /// </summary>
        public static string People_List_EmailOptIn {
            get {
                return ResourceManager.GetString("People_List_EmailOptIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not accept e-mail.
        /// </summary>
        public static string People_List_EmailOptOut {
            get {
                return ResourceManager.GetString("People_List_EmailOptOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Mail.
        /// </summary>
        public static string People_List_MailOptIn {
            get {
                return ResourceManager.GetString("People_List_MailOptIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not accept Mail.
        /// </summary>
        public static string People_List_MailOptOut {
            get {
                return ResourceManager.GetString("People_List_MailOptOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept SMS.
        /// </summary>
        public static string People_List_SMSOptIn {
            get {
                return ResourceManager.GetString("People_List_SMSOptIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not accept SMS.
        /// </summary>
        public static string People_List_SMSOptOut {
            get {
                return ResourceManager.GetString("People_List_SMSOptOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Data.
        /// </summary>
        public static string PersonalData {
            get {
                return ResourceManager.GetString("PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal ID 1.
        /// </summary>
        public static string PersonalId1 {
            get {
                return ResourceManager.GetString("PersonalId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal ID2.
        /// </summary>
        public static string PersonalId2 {
            get {
                return ResourceManager.GetString("PersonalId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 1.
        /// </summary>
        public static string Phone1 {
            get {
                return ResourceManager.GetString("Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 2.
        /// </summary>
        public static string Phone2 {
            get {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 3.
        /// </summary>
        public static string Phone3 {
            get {
                return ResourceManager.GetString("Phone3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        public static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string Register_Date {
            get {
                return ResourceManager.GetString("Register_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Source.
        /// </summary>
        public static string Register_Source {
            get {
                return ResourceManager.GetString("Register_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration completed successfully.
        /// </summary>
        public static string RegisterComplete {
            get {
                return ResourceManager.GetString("RegisterComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name, e-mail or personal id.
        /// </summary>
        public static string Search_Name_PersonalID_Email {
            get {
                return ResourceManager.GetString("Search_Name_PersonalID_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact people administrator.
        /// </summary>
        public static string SecurityPeople_Description {
            get {
                return ResourceManager.GetString("SecurityPeople_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage people.
        /// </summary>
        public static string SecurityPeople_Name {
            get {
                return ResourceManager.GetString("SecurityPeople_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you accept receive newsletter through SMS?.
        /// </summary>
        public static string SMSOptIn {
            get {
                return ResourceManager.GetString("SMSOptIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started_at.
        /// </summary>
        public static string Started_at {
            get {
                return ResourceManager.GetString("Started_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export from.
        /// </summary>
        public static string The_Export_From {
            get {
                return ResourceManager.GetString("The_Export_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group.
        /// </summary>
        public static string User_Group {
            get {
                return ResourceManager.GetString("User_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was finished at.
        /// </summary>
        public static string Was_Finished_At {
            get {
                return ResourceManager.GetString("Was_Finished_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesOptIn {
            get {
                return ResourceManager.GetString("YesOptIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
