//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Box.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedStringsLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStringsLog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Box.Core.SharedStringsLog", typeof(SharedStringsLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0} was created.
        /// </summary>
        internal static string GROUP_CREATION_0 {
            get {
                return ResourceManager.GetString("GROUP_CREATION_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0} was removed.
        /// </summary>
        internal static string GROUP_REMOVE_0 {
            get {
                return ResourceManager.GetString("GROUP_REMOVE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0} was updated.
        /// </summary>
        internal static string GROUP_UPDATE_0 {
            get {
                return ResourceManager.GetString("GROUP_UPDATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} was created.
        /// </summary>
        internal static string USER_CREATION_0 {
            get {
                return ResourceManager.GetString("USER_CREATION_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} password was changed.
        /// </summary>
        internal static string USER_PASSWORD_UPDATE_0 {
            get {
                return ResourceManager.GetString("USER_PASSWORD_UPDATE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} was removed.
        /// </summary>
        internal static string USER_REMOVE_0 {
            get {
                return ResourceManager.GetString("USER_REMOVE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} was updated.
        /// </summary>
        internal static string USER_UPDATE_0 {
            get {
                return ResourceManager.GetString("USER_UPDATE_0", resourceCulture);
            }
        }
    }
}
