//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Box.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Box.Core.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrators.
        /// </summary>
        internal static string Admin_group {
            get {
                return ResourceManager.GetString("Admin_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users of this group has total access to the system..
        /// </summary>
        internal static string Admin_group_description {
            get {
                return ResourceManager.GetString("Admin_group_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string Change_password {
            get {
                return ResourceManager.GetString("Change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not change your password. Probably, your change request has expired..
        /// </summary>
        internal static string Could_not_change_your_password {
            get {
                return ResourceManager.GetString("Could_not_change_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sign in.
        /// </summary>
        internal static string Error_sigin {
            get {
                return ResourceManager.GetString("Error_sigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View system logs.
        /// </summary>
        internal static string LogUserGroup_Description {
            get {
                return ResourceManager.GetString("LogUserGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log viewer.
        /// </summary>
        internal static string LogUserGroup_Name {
            get {
                return ResourceManager.GetString("LogUserGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage groups.
        /// </summary>
        internal static string Manage_groups {
            get {
                return ResourceManager.GetString("Manage_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        internal static string Manage_users {
            get {
                return ResourceManager.GetString("Manage_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds, updates, and remove system users..
        /// </summary>
        internal static string SecurityUserGroup_Description {
            get {
                return ResourceManager.GetString("SecurityUserGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User admin.
        /// </summary>
        internal static string SecurityUserGroup_Name {
            get {
                return ResourceManager.GetString("SecurityUserGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized user. Contact the system administrator..
        /// </summary>
        internal static string Unauthorized_UserNT {
            get {
                return ResourceManager.GetString("Unauthorized_UserNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have an active account at this system.
        /// </summary>
        internal static string You_do_not_have_an_active_account_at_this_system {
            get {
                return ResourceManager.GetString("You_do_not_have_an_active_account_at_this_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was changed..
        /// </summary>
        internal static string Your_password_was_changed {
            get {
                return ResourceManager.GetString("Your_password_was_changed", resourceCulture);
            }
        }
    }
}
