//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Box.Adm.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show other groups.
        /// </summary>
        public static string Add_more_groups {
            get {
                return ResourceManager.GetString("Add_more_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more permissions.
        /// </summary>
        public static string Add_more_permissions {
            get {
                return ResourceManager.GetString("Add_more_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An e-mail was send to you with your new password..
        /// </summary>
        public static string An_email_was_send_to_you_with_your_new_password {
            get {
                return ResourceManager.GetString("An_email_was_send_to_you_with_your_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Are_you_sure {
            get {
                return ResourceManager.GetString("Are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel network login change.
        /// </summary>
        public static string Cancel_network_login_change {
            get {
                return ResourceManager.GetString("Cancel_network_login_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel password change.
        /// </summary>
        public static string Cancel_password_change {
            get {
                return ResourceManager.GetString("Cancel_password_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change/Define network login.
        /// </summary>
        public static string Change_Network_Login {
            get {
                return ResourceManager.GetString("Change_Network_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change/Define password.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find your user account..
        /// </summary>
        public static string Could_not_find_your_user_account {
            get {
                return ResourceManager.GetString("Could_not_find_your_user_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sign in.
        /// </summary>
        public static string Error_sigin {
            get {
                return ResourceManager.GetString("Error_sigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string Export_Data {
            get {
                return ResourceManager.GetString("Export_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Forgot_your_password {
            get {
                return ResourceManager.GetString("Forgot_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group unbound permission.
        /// </summary>
        public static string Group_Has_No_Permission {
            get {
                return ResourceManager.GetString("Group_Has_No_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group permission.
        /// </summary>
        public static string Group_Permission {
            get {
                return ResourceManager.GetString("Group_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search group  by name or permission.
        /// </summary>
        public static string Group_Search_By_Name_Permission {
            get {
                return ResourceManager.GetString("Group_Search_By_Name_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group has not any permission.
        /// </summary>
        public static string Group_Without_Any_Permission {
            get {
                return ResourceManager.GetString("Group_Without_Any_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide other groups.
        /// </summary>
        public static string Hide_other_groups {
            get {
                return ResourceManager.GetString("Hide_other_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide permissions.
        /// </summary>
        public static string Hide_permissions {
            get {
                return ResourceManager.GetString("Hide_permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user or password.
        /// </summary>
        public static string Invalid_user_or_password {
            get {
                return ResourceManager.GetString("Invalid_user_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wait....
        /// </summary>
        public static string Loading_data {
            get {
                return ResourceManager.GetString("Loading_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create user. Another user with same network Login already exists..
        /// </summary>
        public static string LoginNT_already_exists {
            get {
                return ResourceManager.GetString("LoginNT_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you are using one of the following browsers.
        /// </summary>
        public static string Make_sure_you_are_using_one_of_the_following_browsers {
            get {
                return ResourceManager.GetString("Make_sure_you_are_using_one_of_the_following_browsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        public static string Manage_users {
            get {
                return ResourceManager.GetString("Manage_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to.
        /// </summary>
        public static string Move_to {
            get {
                return ResourceManager.GetString("Move_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for name, email or user group.
        /// </summary>
        public static string Name_email_or_group {
            get {
                return ResourceManager.GetString("Name_email_or_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Login (ex:dominio\usuario).
        /// </summary>
        public static string Network_Login {
            get {
                return ResourceManager.GetString("Network_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New group.
        /// </summary>
        public static string New_group {
            get {
                return ResourceManager.GetString("New_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string New_password {
            get {
                return ResourceManager.GetString("New_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        public static string New_user {
            get {
                return ResourceManager.GetString("New_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próximo.
        /// </summary>
        public static string Next_navigation {
            get {
                return ResourceManager.GetString("Next_navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more groups to add..
        /// </summary>
        public static string No_groups_to_add {
            get {
                return ResourceManager.GetString("No_groups_to_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items were found.
        ///Try to change your filter..
        /// </summary>
        public static string No_items_were_found {
            get {
                return ResourceManager.GetString("No_items_were_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or login with windows account..
        /// </summary>
        public static string Or_Login_with_windows_account {
            get {
                return ResourceManager.GetString("Or_Login_with_windows_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using.
        /// </summary>
        public static string Or_using {
            get {
                return ResourceManager.GetString("Or_using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by.
        /// </summary>
        public static string Order_by {
            get {
                return ResourceManager.GetString("Order_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other groups.
        /// </summary>
        public static string Other_groups {
            get {
                return ResourceManager.GetString("Other_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-typed it.
        /// </summary>
        public static string Password_check {
            get {
                return ResourceManager.GetString("Password_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not required when using other authertication providers, such as Windows Live, Google....
        /// </summary>
        public static string Password_tooltip {
            get {
                return ResourceManager.GetString("Password_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was changed..
        /// </summary>
        public static string Password_was_changed {
            get {
                return ResourceManager.GetString("Password_was_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go to.
        /// </summary>
        public static string Please_go_to {
            get {
                return ResourceManager.GetString("Please_go_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove group.
        /// </summary>
        public static string Remove_group {
            get {
                return ResourceManager.GetString("Remove_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove user.
        /// </summary>
        public static string Remove_user {
            get {
                return ResourceManager.GetString("Remove_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Reset_password {
            get {
                return ResourceManager.GetString("Reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your e-mail account. A new password and an activate link will be send to your e-mail..
        /// </summary>
        public static string Reset_password_tooltip {
            get {
                return ResourceManager.GetString("Reset_password_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested a new password. A new password was generate to you, but it will only be activated once you click at the activate link bellow..
        /// </summary>
        public static string Reset_password_tooltip2 {
            get {
                return ResourceManager.GetString("Reset_password_tooltip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for user or event.
        /// </summary>
        public static string Search_for_user_or_event {
            get {
                return ResourceManager.GetString("Search_for_user_or_event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Sign_in {
            get {
                return ResourceManager.GetString("Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in again.
        /// </summary>
        public static string Sign_in_again {
            get {
                return ResourceManager.GetString("Sign_in_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Sign_out {
            get {
                return ResourceManager.GetString("Sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing....
        /// </summary>
        public static string Signing {
            get {
                return ResourceManager.GetString("Signing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group &quot;.
        /// </summary>
        public static string The_group_X {
            get {
                return ResourceManager.GetString("The_group_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &quot;.
        /// </summary>
        public static string The_user_X {
            get {
                return ResourceManager.GetString("The_user_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of log.
        /// </summary>
        public static string Type_of_log {
            get {
                return ResourceManager.GetString("Type_of_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized user. Contact the system administrator..
        /// </summary>
        public static string Unauthorized_UserNT {
            get {
                return ResourceManager.GetString("Unauthorized_UserNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create user. Another user with same e-mail or same network login already exists..
        /// </summary>
        public static string User_already_exists {
            get {
                return ResourceManager.GetString("User_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user account is blocked..
        /// </summary>
        public static string User_blocked {
            get {
                return ResourceManager.GetString("User_blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users&apos; groups.
        /// </summary>
        public static string User_groups {
            get {
                return ResourceManager.GetString("User_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has no groups..
        /// </summary>
        public static string User_has_no_groups {
            get {
                return ResourceManager.GetString("User_has_no_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string val_Please_enter_a_valid_email_address {
            get {
                return ResourceManager.GetString("val_Please_enter_a_valid_email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid URL..
        /// </summary>
        public static string val_Please_enter_a_valid_URL {
            get {
                return ResourceManager.GetString("val_Please_enter_a_valid_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least {0} characters..
        /// </summary>
        public static string val_Please_enter_at_least_X_characters {
            get {
                return ResourceManager.GetString("val_Please_enter_at_least_X_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string val_This_field_is_required {
            get {
                return ResourceManager.GetString("val_This_field_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votos.
        /// </summary>
        public static string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot; will be removed..
        /// </summary>
        public static string will_be_removed {
            get {
                return ResourceManager.GetString("will_be_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use Gravatar to change your profile picture.
        /// </summary>
        public static string You_can_use_Gravatar_to_change_your_picture {
            get {
                return ResourceManager.GetString("You_can_use_Gravatar_to_change_your_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have an active account at this system.
        /// </summary>
        public static string You_do_not_have_an_active_account_at_this_system {
            get {
                return ResourceManager.GetString("You_do_not_have_an_active_account_at_this_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credentials.
        /// </summary>
        public static string Your_crendetials {
            get {
                return ResourceManager.GetString("Your_crendetials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email.
        /// </summary>
        public static string Your_email {
            get {
                return ResourceManager.GetString("Your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password is.
        /// </summary>
        public static string Your_new_password_is {
            get {
                return ResourceManager.GetString("Your_new_password_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password.
        /// </summary>
        public static string Your_password {
            get {
                return ResourceManager.GetString("Your_password", resourceCulture);
            }
        }
    }
}
