//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Box.CMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Box.CMS.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        public static string Abstract {
            get {
                return ResourceManager.GetString("Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add content.
        /// </summary>
        public static string add_content {
            get {
                return ResourceManager.GetString("add_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any kind.
        /// </summary>
        public static string Any_kind {
            get {
                return ResourceManager.GetString("Any_kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any time.
        /// </summary>
        public static string Any_time {
            get {
                return ResourceManager.GetString("Any_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply and Publish.
        /// </summary>
        public static string Apply_and_Publish {
            get {
                return ResourceManager.GetString("Apply_and_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at .
        /// </summary>
        public static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audios.
        /// </summary>
        public static string Audios {
            get {
                return ResourceManager.GetString("Audios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best ranked.
        /// </summary>
        public static string Best_ranked {
            get {
                return ResourceManager.GetString("Best_ranked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        public static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Abstract.
        /// </summary>
        public static string Change_Abstract {
            get {
                return ResourceManager.GetString("Change_Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds, removes and updates any file..
        /// </summary>
        public static string CMSFILEUserGroup_Description {
            get {
                return ResourceManager.GetString("CMSFILEUserGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS File Admin.
        /// </summary>
        public static string CMSFILEUserGroup_Name {
            get {
                return ResourceManager.GetString("CMSFILEUserGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds, removes and updates any content..
        /// </summary>
        public static string CMSUserGroup_Description {
            get {
                return ResourceManager.GetString("CMSUserGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS Admin.
        /// </summary>
        public static string CMSUserGroup_Name {
            get {
                return ResourceManager.GetString("CMSUserGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content date.
        /// </summary>
        public static string Content_date {
            get {
                return ResourceManager.GetString("Content_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPIRED.
        /// </summary>
        public static string CONTENT_EXPIRED {
            get {
                return ResourceManager.GetString("CONTENT_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content name or description.
        /// </summary>
        public static string Content_name_or_description {
            get {
                return ResourceManager.GetString("Content_name_or_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT PUBLISHED.
        /// </summary>
        public static string CONTENT_NOT_PUBLISHED {
            get {
                return ResourceManager.GetString("CONTENT_NOT_PUBLISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        public static string Content_period {
            get {
                return ResourceManager.GetString("Content_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULED.
        /// </summary>
        public static string CONTENT_SCHEDULED {
            get {
                return ResourceManager.GetString("CONTENT_SCHEDULED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created at.
        /// </summary>
        public static string created_at {
            get {
                return ResourceManager.GetString("created_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop image.
        /// </summary>
        public static string Crop_image {
            get {
                return ResourceManager.GetString("Crop_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move and scale the image to crop.
        /// </summary>
        public static string Crop_tooltip {
            get {
                return ResourceManager.GetString("Crop_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Links.
        /// </summary>
        public static string Cross_Links {
            get {
                return ResourceManager.GetString("Cross_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content will also appear at the following cross-links:.
        /// </summary>
        public static string Cross_Links_tooltip {
            get {
                return ResourceManager.GetString("Cross_Links_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drag and drop files here.
        /// </summary>
        public static string drag_and_drop_files_here {
            get {
                return ResourceManager.GetString("drag_and_drop_files_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or image name.
        /// </summary>
        public static string File_or_image_name {
            get {
                return ResourceManager.GetString("File_or_image_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload.
        /// </summary>
        public static string File_upload {
            get {
                return ResourceManager.GetString("File_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hour(s) ago.
        /// </summary>
        public static string hours_ago {
            get {
                return ResourceManager.GetString("hours_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 12 months.
        /// </summary>
        public static string Last_12_months {
            get {
                return ResourceManager.GetString("Last_12_months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 6 months.
        /// </summary>
        public static string Last_6_months {
            get {
                return ResourceManager.GetString("Last_6_months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        public static string Last_month {
            get {
                return ResourceManager.GetString("Last_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        public static string Last_week {
            get {
                return ResourceManager.GetString("Last_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less popular.
        /// </summary>
        public static string Less_popular {
            get {
                return ResourceManager.GetString("Less_popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less viewed.
        /// </summary>
        public static string Less_Viewed {
            get {
                return ResourceManager.GetString("Less_Viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External link starting with http://.
        /// </summary>
        public static string Link_tooltip {
            get {
                return ResourceManager.GetString("Link_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to live update.
        /// </summary>
        public static string live_update {
            get {
                return ResourceManager.GetString("live_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes(s) ago.
        /// </summary>
        public static string minutes_ago {
            get {
                return ResourceManager.GetString("minutes_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most popular.
        /// </summary>
        public static string Most_popular {
            get {
                return ResourceManager.GetString("Most_popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most viewed.
        /// </summary>
        public static string Most_Viewed {
            get {
                return ResourceManager.GetString("Most_Viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move left.
        /// </summary>
        public static string Move_left {
            get {
                return ResourceManager.GetString("Move_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move right.
        /// </summary>
        public static string Move_right {
            get {
                return ResourceManager.GetString("Move_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string New_comment {
            get {
                return ResourceManager.GetString("New_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        public static string New_file {
            get {
                return ResourceManager.GetString("New_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        public static string Newest {
            get {
                return ResourceManager.GetString("Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contents were found for this cross link.
        /// </summary>
        public static string No_contents_were_found_for_this_crosslink {
            get {
                return ResourceManager.GetString("No_contents_were_found_for_this_crosslink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        public static string Oldest {
            get {
                return ResourceManager.GetString("Oldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to published only.
        /// </summary>
        public static string Only_published {
            get {
                return ResourceManager.GetString("Only_published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or use media database.
        /// </summary>
        public static string or_use_image_database {
            get {
                return ResourceManager.GetString("or_use_image_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define_the_content_date_or_an_arbitrary_order.
        /// </summary>
        public static string Order_by_tooltip {
            get {
                return ResourceManager.GetString("Order_by_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication.
        /// </summary>
        public static string Publication {
            get {
                return ResourceManager.GetString("Publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish after.
        /// </summary>
        public static string Publish_after {
            get {
                return ResourceManager.GetString("Publish_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you publish this content it will be avaiable at the web-site.
        ///Are you sure you want to publish it now?.
        /// </summary>
        public static string Publish_alert {
            get {
                return ResourceManager.GetString("Publish_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish_tooltip {
            get {
                return ResourceManager.GetString("Publish_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish until.
        /// </summary>
        public static string Publish_until {
            get {
                return ResourceManager.GetString("Publish_until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative.
        /// </summary>
        public static string Quiz_Alternative {
            get {
                return ResourceManager.GetString("Quiz_Alternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatives.
        /// </summary>
        public static string Quiz_Alternatives {
            get {
                return ResourceManager.GetString("Quiz_Alternatives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes to zero.
        /// </summary>
        public static string Quiz_Clear_Votes {
            get {
                return ResourceManager.GetString("Quiz_Clear_Votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Quiz_Question {
            get {
                return ResourceManager.GetString("Quiz_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string Quiz_Vote {
            get {
                return ResourceManager.GetString("Quiz_Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading comments....
        /// </summary>
        public static string reading_comments {
            get {
                return ResourceManager.GetString("reading_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove content.
        /// </summary>
        public static string Remove_content {
            get {
                return ResourceManager.GetString("Remove_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove file.
        /// </summary>
        public static string Remove_file {
            get {
                return ResourceManager.GetString("Remove_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  second(s) ago.
        /// </summary>
        public static string seconds_ago {
            get {
                return ResourceManager.GetString("seconds_ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a content.
        /// </summary>
        public static string Select_a_content {
            get {
                return ResourceManager.GetString("Select_a_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file.
        /// </summary>
        public static string Select_a_file {
            get {
                return ResourceManager.GetString("Select_a_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an image.
        /// </summary>
        public static string Select_an_image {
            get {
                return ResourceManager.GetString("Select_an_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending files....
        /// </summary>
        public static string Sending_files {
            get {
                return ResourceManager.GetString("Sending_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop live update.
        /// </summary>
        public static string stop_live_update {
            get {
                return ResourceManager.GetString("stop_live_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags that will be used to help user to find this content.
        /// </summary>
        public static string Tags_tooltip {
            get {
                return ResourceManager.GetString("Tags_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content &quot;.
        /// </summary>
        public static string The_content_X {
            get {
                return ResourceManager.GetString("The_content_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;.
        /// </summary>
        public static string The_file_X {
            get {
                return ResourceManager.GetString("The_file_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top banner.
        /// </summary>
        public static string Top_banner {
            get {
                return ResourceManager.GetString("Top_banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Despublicar.
        /// </summary>
        public static string Unpublish {
            get {
                return ResourceManager.GetString("Unpublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are seeing this message because your browser does not support ajax upload..
        /// </summary>
        public static string Upload_not_supported_tooltip_1 {
            get {
                return ResourceManager.GetString("Upload_not_supported_tooltip_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider use other browsers such as Google Chrome, FireFox or IE 10 for a better upload expiriense..
        /// </summary>
        public static string Upload_not_supported_tooltip_2 {
            get {
                return ResourceManager.GetString("Upload_not_supported_tooltip_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... more.
        /// </summary>
        public static string view_full_comment {
            get {
                return ResourceManager.GetString("view_full_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing content at.
        /// </summary>
        public static string Viewing_content_at {
            get {
                return ResourceManager.GetString("Viewing_content_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploaded ok.
        /// </summary>
        public static string was_uploaded {
            get {
                return ResourceManager.GetString("was_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worst ranked.
        /// </summary>
        public static string Worst_ranked {
            get {
                return ResourceManager.GetString("Worst_ranked", resourceCulture);
            }
        }
    }
}
