//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Box.CMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStringsLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStringsLog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Box.CMS.SharedStringsLog", typeof(SharedStringsLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; was created.
        /// </summary>
        public static string CONTENT_0_CREATION_1 {
            get {
                return ResourceManager.GetString("CONTENT_0_CREATION_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; was removed.
        /// </summary>
        public static string CONTENT_0_REMOVE_1 {
            get {
                return ResourceManager.GetString("CONTENT_0_REMOVE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; was updated.
        /// </summary>
        public static string CONTENT_0_UPDATE_1 {
            get {
                return ResourceManager.GetString("CONTENT_0_UPDATE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-link {0} &apos;{1}&apos; was removed.
        /// </summary>
        public static string CROSSLINK_0_REMOVE_1 {
            get {
                return ResourceManager.GetString("CROSSLINK_0_REMOVE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; was removed from folder &apos;{1}&apos;.
        /// </summary>
        public static string FILE_REMOVE_0_1 {
            get {
                return ResourceManager.GetString("FILE_REMOVE_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s) were uploaded to folder &apos;{0}&apos;.
        /// </summary>
        public static string FILE_UPLOAD {
            get {
                return ResourceManager.GetString("FILE_UPLOAD", resourceCulture);
            }
        }
    }
}
